BEGIN;

ALTER TABLE posts
  ADD COLUMN IF NOT EXISTS image_delivery_type VARCHAR(20) NOT NULL DEFAULT 'upload',
  ADD COLUMN IF NOT EXISTS image_version BIGINT NULL,
  ADD COLUMN IF NOT EXISTS image_width INTEGER NULL,
  ADD COLUMN IF NOT EXISTS image_height INTEGER NULL,
  ADD COLUMN IF NOT EXISTS image_format VARCHAR(20) NULL,
  ADD COLUMN IF NOT EXISTS image_bytes INTEGER NULL;

COMMIT;